"use client";

import { useEffect, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  RotateCcw, FileSearch, Check, X, Pencil, FileText,
  Pill, AlertTriangle, MessageSquare, BadgeCheck, ShieldCheck, Sparkles,
  User,
} from "lucide-react";
import { useAppStore } from "@/store";
import { DoctorPageShell } from "@/layouts/DoctorPageShell";
import { Button } from "@/components/ui/button";
import { StatusBadge, statusVariant } from "@/components/shared/StatusBadge";
import { cn } from "@/utils";
import { uid } from "@/lib/brand/constants";
import { SUMMARY_SERVICE } from "@/services/summaryGeneratorService";
import type { ClinicalNote, DoctorPatientRecord, PrescriptionDraft } from "@/types";

type Tab = "summary" | "notes" | "rx" | "redflags";

const summaryFields: { key: string; label: string }[] = [
  { key: "chiefComplaint", label: "Chief Complaint" },
  { key: "hpi", label: "History of Present Illness" },
  { key: "pastMedicalHistory", label: "Past Medical History" },
  { key: "medications", label: "Current Medications" },
  { key: "allergies", label: "Allergies" },
  { key: "familyHistory", label: "Family History" },
  { key: "investigations", label: "Investigations" },
  { key: "timeline", label: "Timeline" },
  { key: "redFlags", label: "Red Flags" },
];

export function DoctorPatientView() {
  const setView = useAppStore((s) => s.setView);
  const selectedPatientId = useAppStore((s) => s.selectedPatientId);
  const setSelectedPatientId = useAppStore((s) => s.setSelectedPatientId);
  const currentTab = useAppStore((s) => s.currentView as never);
  const caseQueue = useAppStore((s) => s.caseQueue);
  const updateCaseRecord = useAppStore((s) => s.updateCaseRecord);
  const doctor = useAppStore((s) => s.doctorProfile);

  // Source evidence for the "View Evidence" drawer. Only the real, source-traceable
  // evidence generated by the AI history interview is shown — never fabricated rows.
  const evidence = useAppStore((s) =>
    s.intakeSession?.summary?.sourceEvidence?.length
      ? s.intakeSession.summary.sourceEvidence
      : []
  );

  const patient = caseQueue.find((p) => p.id === selectedPatientId) ?? caseQueue[0];

  const [tab, setTab] = useState<Tab>("summary");
  const [evidenceOpen, setEvidenceOpen] = useState(false);
  const [verdict, setVerdict] = useState<"none" | "accepted" | "edited" | "rejected">(patient?.aiSummary?.verified ? "accepted" : "none");
  const [note, setNote] = useState("");
  const [rejectOpen, setRejectOpen] = useState(false);
  const [regenerating, setRegenerating] = useState(false);

  const savedNotes = patient?.notes ?? [];
  const openNotes = savedNotes.filter((n) => n.type !== "follow-up");
  const followups = savedNotes.filter((n) => n.type === "follow-up");
  const rx: PrescriptionDraft[] = (patient?.prescriptions?.length ? patient.prescriptions : [{ medicine: "", dose: "", frequency: "", duration: "", confirmed: false }]);
  const confirmRf = Object.fromEntries((patient?.redFlags ?? []).map((rf) => [rf.id, rf.status === "reviewed"]));
  const escalated = Object.fromEntries((patient?.redFlags ?? []).map((rf) => [rf.id, rf.status === "escalated"]));

  useEffect(() => {
    if (!regenerating) return;
    const id = setTimeout(() => setRegenerating(false), 1200);
    return () => clearTimeout(id);
  }, [regenerating]);

  const regenerateAi = async () => {
    const intake = useAppStore.getState().intakeSession;
    if (!intake?.clinicalHistory && !intake?.conversationTurns?.length) {
      return;
    }
    setRegenerating(true);
    const summary = await SUMMARY_SERVICE.generate(
      patient.id,
      intake.clinicalHistory,
      intake.documents,
      intake.redFlags,
      intake.historyMode,
      intake.conversationTurns
    );
    // Mirror the regenerated summary into the case's AI summary for clinician review.
    updateCaseRecord(patient.id, {
      aiSummary: {
        chiefComplaint: summary.chiefComplaint,
        hpi: summary.hpi,
        pastMedicalHistory: summary.pastMedicalHistory,
        medications: summary.currentMedications,
        allergies: summary.allergies,
        familyHistory: summary.familyHistory,
        investigations: summary.investigationHighlights,
        redFlags: summary.redFlags,
        generatedAt: summary.generatedAt,
        verified: false,
      },
    });
    setRegenerating(false);
  };

  if (!patient) {
    return (
      <DoctorPageShell title="Patient" currentTab={currentTab as string} onBack={() => setView("DOCTOR_QUEUE")}>
        <div className="rounded-2xl border-2 border-dashed border-border py-10 text-center">
          <p className="text-sm font-medium text-muted-foreground">No patient selected</p>
          <p className="mt-1 text-xs text-muted-foreground">Choose a patient from the queue.</p>
        </div>
      </DoctorPageShell>
    );
  }

  const setRx = (arr: PrescriptionDraft[]) => updateCaseRecord(patient.id, { prescriptions: arr });
  const addRxRow = () => setRx([...rx, { medicine: "", dose: "", frequency: "", duration: "", confirmed: false }]);

  const addAudit = (p: DoctorPatientRecord, action: string, detail?: string) => {
    useAppStore.getState().addAuditEvent({
      id: uid("audit"),
      actor: doctor?.name ?? "Doctor",
      role: "DOCTOR",
      action,
      targetType: "DoctorPatientRecord",
      targetId: p.id,
      detail: detail ?? `${p.name} (${p.patientId})`,
      timestamp: new Date().toISOString(),
    });
  };

  const applyVerdict = (v: "accepted" | "edited" | "rejected") => {
    setVerdict(v);
    const verified = v === "accepted";
    updateCaseRecord(patient.id, {
      summaryStatus: v === "rejected" ? "pending" : "verified",
      summaryVerified: verified,
      verifiedBy: doctor?.name ?? "Doctor",
      verifiedAt: new Date().toISOString(),
      aiSummary: { ...patient.aiSummary, verified, verifiedBy: doctor?.name ?? "Doctor" },
    });
    addAudit(patient, "SUMMARY_VERIFIED", `${v} · ${patient.name}`);
  };

  const saveNote = (type: "note" | "follow-up") => {
    if (!note.trim()) return;
    const n: ClinicalNote = { id: uid("note"), type, content: note.trim(), timestamp: new Date().toISOString(), status: "saved" };
    updateCaseRecord(patient.id, { notes: [...savedNotes, n] });
    setNote("");
    addAudit(patient, type === "follow-up" ? "FOLLOWUP_CREATED" : "NOTE_SAVED", note.trim());
  };

  const toggleRedFlag = (rfId: string, status: "reviewed" | "escalated") => {
    updateCaseRecord(patient.id, {
      redFlags: (patient.redFlags ?? []).map((rf) =>
        rf.id === rfId ? { ...rf, status: rf.status === status ? "open" : status } : rf
      ),
    });
  };

  const summon = (id: string) => {
    setSelectedPatientId(id);
    setTab("summary");
  };

  return (
    <DoctorPageShell title={patient.name} currentTab={currentTab as string} sub={`${patient.age} · ${patient.gender} · ${patient.patientId}`}
      onBack={() => setView("DOCTOR_QUEUE")}
      right={<StatusBadge variant={statusVariant(patient.redFlagLevel ?? "NORMAL")} dot>{patient.redFlagLevel?.replace("_", " ")}</StatusBadge>}>

      {/* Tabs */}
      <div className="mb-4 flex gap-1 overflow-x-auto no-scrollbar rounded-xl bg-muted/70 p-1">
        {([
          ["summary", "AI Summary"],
          ["notes", "Notes"],
          ["rx", "Prescription"],
          ["redflags", "Red Flags"],
        ] as [Tab, string][]).map(([k, label]) => (
          <button key={k} onClick={() => setTab(k)}
            className={cn("flex-1 shrink-0 rounded-lg px-2 py-2 text-xs font-semibold transition-colors", tab === k ? "bg-card shadow-sm" : "text-muted-foreground")}>
            {label}
          </button>
        ))}
      </div>

      {/* ============ AI SUMMARY ============ */}
      {tab === "summary" && (
        <div>
          <div className="mt-4 flex items-center justify-between">
            <h2 className="flex items-center gap-1.5 text-sm font-semibold">
              <Sparkles className="size-4 text-primary" /> AI Draft Summary
            </h2>
            <button onClick={() => setEvidenceOpen(!evidenceOpen)}
              className="flex items-center gap-1 rounded-lg bg-primary/10 px-2.5 py-1.5 text-xs font-medium text-primary">
              <FileSearch className="size-3.5" /> {evidenceOpen ? "Hide" : "View"} Evidence
            </button>
          </div>

          {/* Verification banner */}
          {patient.summaryStatus === "pending" && (
            <div className="mt-3 flex items-center gap-2 rounded-xl border border-amber-300/50 bg-amber-50 p-2.5 text-xs text-amber-800 dark:bg-amber-500/10 dark:text-amber-300">
              <AlertTriangle className="size-4" /> This AI summary is a draft and has not been verified by a clinician.
            </div>
          )}

          <div className="mt-3 space-y-2.5">
            {summaryFields.map((f) => {
              const val = patient.aiSummary?.[f.key as keyof typeof patient.aiSummary];
              return (
                <div key={f.key} className="rounded-xl border border-border bg-card p-3 card-soft">
                  <p className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">{f.label}</p>
                  {typeof val === "string" && val ? (
                    <p className="mt-1 text-sm">{val}</p>
                  ) : (
                    <p className="mt-1 text-sm italic text-muted-foreground">Not provided</p>
                  )}
                </div>
              );
            })}
          </div>

          {/* Source evidence button / drawer */}
          <div className="mt-4 flex items-start gap-2 rounded-xl border border-primary/15 bg-primary/5 p-3 text-xs text-muted-foreground">
            <ShieldCheck className="mt-0.5 size-4 shrink-0 text-primary" />
            <p>AI-generated draft for clinician review. Verify or edit before accepting into the record.</p>
          </div>

          {evidenceOpen && (
            <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} className="mt-3 overflow-hidden">
              <div className="rounded-2xl border border-border bg-card p-3 card-soft">
                <p className="mb-2 flex items-center gap-1.5 text-xs font-semibold"><FileSearch className="size-4 text-primary" /> Source Evidence</p>
                {evidence.length === 0 ? (
                  <p className="text-xs text-muted-foreground">No source evidence is available yet. Complete an AI history interview to generate evidence.</p>
                ) : (
                  evidence.map((s, i) => (
                    <div key={i} className="mb-2 rounded-lg bg-muted/40 p-2.5">
                      <div className="flex items-center justify-between">
                        <p className="text-[10px] font-bold uppercase text-muted-foreground">{s.field}</p>
                        <span className="rounded-md bg-primary/10 px-1.5 py-0.5 text-[10px] font-semibold text-primary">{s.status?.replace("-", " ")}</span>
                      </div>
                      <p className="mt-1 text-xs">{s.value}</p>
                      <p className="mt-0.5 text-[10px] text-muted-foreground">Source: {s.source ?? "AI Interview"}</p>
                    </div>
                  ))
                )}
              </div>
            </motion.div>
          )}

          {/* Verdict buttons */}
          <div className="mt-4 grid grid-cols-3 gap-2">
            <VerdictBtn icon={Check} label="Accept" active={verdict === "accepted"} tone="emerald" onClick={() => applyVerdict("accepted")} />
            <VerdictBtn icon={Pencil} label="Edit" active={verdict === "edited"} tone="sky" onClick={() => applyVerdict("edited")} />
            <VerdictBtn icon={X} label="Reject" active={verdict === "rejected"} tone="red" onClick={() => setRejectOpen(true)} />
          </div>

          <AnimatePresence>
            {rejectOpen && (
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                className="mt-3 rounded-2xl border border-red-300/60 bg-red-50 p-3 dark:border-red-500/40 dark:bg-red-500/10">
                <p className="text-sm font-semibold text-red-800 dark:text-red-300">Reject AI summary?</p>
                <p className="mt-1 text-xs text-red-700/80 dark:text-red-300/80">The draft will be discarded and flagged for manual review.</p>
                <div className="mt-3 flex gap-2">
                  <Button variant="outline" className="flex-1" onClick={() => setRejectOpen(false)}>Cancel</Button>
                  <Button variant="destructive" className="flex-1" onClick={() => { applyVerdict("rejected"); setRejectOpen(false); }}>Confirm reject</Button>
                </div>
              </motion.div>
            )}
          </AnimatePresence>

          {verdict === "accepted" && <VerifiedBanner text={`Summary verified and accepted by ${doctor?.name ?? "Doctor"}`} />}
          {verdict === "edited" && <VerifiedBanner text="Summary captured with clinician edits" />}
          {verdict === "rejected" && (
            <div className="mt-3 rounded-xl border border-red-300/50 bg-red-50 p-3 text-xs text-red-800 dark:bg-red-500/10 dark:text-red-300">
              Summary rejected and flagged for manual clinician review.
            </div>
          )}
        </div>
      )}

      {/* ============ NOTES ============ */}
      {tab === "notes" && (
        <div>
          <h2 className="flex items-center gap-1.5 text-sm font-semibold"><MessageSquare className="size-4 text-primary" /> Clinical Notes</h2>
          <div className="mt-3 rounded-2xl border border-border bg-card p-3 card-soft">
            <p className="mb-2 text-xs font-semibold text-muted-foreground">Add note</p>
            <textarea value={note} onChange={(e) => setNote(e.target.value)} rows={3}
              placeholder="Assessment, plan, follow-up…"
              className="w-full rounded-xl border border-input bg-card px-3 py-2 text-sm outline-none focus:border-ring" />
            <div className="mt-2 flex gap-2">
              <Button className="flex-1" onClick={() => saveNote("note")}>Save note</Button>
              <Button variant="outline" onClick={() => saveNote("follow-up")}>Add follow-up</Button>
            </div>
          </div>

          {openNotes.length > 0 && <NoteList title="Assessment / Plan" items={openNotes} />}
          {followups.length > 0 && <NoteList title="Follow-ups" items={followups} />}
        </div>
      )}

      {/* ============ PRESCRIPTIONS ============ */}
      {tab === "rx" && (
        <div>
          <h2 className="flex items-center gap-1.5 text-sm font-semibold"><Pill className="size-4 text-primary" /> Prescription Draft</h2>
          <div className="mt-3 space-y-2.5">
            {rx.map((r, i) => (
              <div key={i} className="rounded-2xl border border-border bg-card p-3 card-soft">
                <div className="mb-2 flex items-center justify-between">
                  <span className="text-xs font-semibold text-muted-foreground">Medicine {i + 1}</span>
                  {i > 0 && (
                    <button onClick={() => setRx(rx.filter((_, j) => j !== i))} className="text-red-500"><X className="size-4" /></button>
                  )}
                </div>
                <div className="grid grid-cols-2 gap-2">
                  <input value={r.medicine} onChange={(e) => setRx(rx.map((x, j) => j === i ? { ...x, medicine: e.target.value } : x))}
                    placeholder="Medicine name" className="col-span-2 rounded-lg border border-input bg-card px-3 py-2 text-sm outline-none focus:border-ring" />
                  <input value={r.dose} onChange={(e) => setRx(rx.map((x, j) => j === i ? { ...x, dose: e.target.value } : x))}
                    placeholder="Dose (e.g. 5 mg)" className="rounded-lg border border-input bg-card px-3 py-2 text-sm outline-none focus:border-ring" />
                  <input value={r.frequency} onChange={(e) => setRx(rx.map((x, j) => j === i ? { ...x, frequency: e.target.value } : x))}
                    placeholder="Frequency" className="rounded-lg border border-input bg-card px-3 py-2 text-sm outline-none focus:border-ring" />
                  <input value={r.duration} onChange={(e) => setRx(rx.map((x, j) => j === i ? { ...x, duration: e.target.value } : x))}
                    placeholder="Duration" className="col-span-2 rounded-lg border border-input bg-card px-3 py-2 text-sm outline-none focus:border-ring" />
                </div>
              </div>
            ))}
          </div>
          <div className="mt-3 grid grid-cols-2 gap-2">
            <Button variant="outline" onClick={addRxRow}>+ Add medicine</Button>
            <Button className="flex items-center gap-1.5" onClick={() => { setRx(rx.map((r) => ({ ...r, confirmed: true }))); addAudit(patient, "PRESCRIPTION_FINALIZED"); setView("DOCTOR_PRESCRIPTIONS"); }}>
              <FileText className="size-4" /> Finalize script
            </Button>
          </div>
        </div>
      )}

      {/* ============ RED FLAGS ============ */}
      {tab === "redflags" && (
        <div>
          <h2 className="flex items-center gap-1.5 text-sm font-semibold"><AlertTriangle className="size-4 text-primary" /> Red Flags</h2>
          <div className="mt-3 space-y-2.5">
            {(patient.redFlags?.length ? patient.redFlags : []).map((rf) => (
              <div key={rf.id} className={cn("rounded-2xl border p-3.5 card-soft",
                rf.level === "URGENT" ? "border-red-300/60 bg-red-50 dark:bg-red-500/10" : "border-amber-300/60 bg-amber-50 dark:bg-amber-500/10")}>
                <div className="flex items-center justify-between">
                  <span className="font-mono text-xs font-bold uppercase tracking-wide">{rf.rule}</span>
                  <StatusBadge variant={statusVariant(rf.level)} dot>{rf.level.replace("_", " ")}</StatusBadge>
                </div>
                <p className="mt-1.5 text-sm">{rf.reason}</p>
                <p className="mt-1 text-[10px] text-muted-foreground">Detected: {rf.timestamp}</p>
                <div className="mt-2.5 flex flex-wrap gap-1.5 border-t border-border/60 pt-2.5">
                  <button onClick={() => toggleRedFlag(rf.id, "reviewed")}
                    className={cn("rounded-lg px-2.5 py-1.5 text-xs font-medium", confirmRf[rf.id] ? "bg-emerald-500 text-white" : "bg-muted")}>
                    {confirmRf[rf.id] ? "Confirmed" : "Confirm"}
                  </button>
                  <button onClick={() => toggleRedFlag(rf.id, "escalated")}
                    className={cn("rounded-lg px-2.5 py-1.5 text-xs font-medium", escalated[rf.id] ? "bg-red-500 text-white" : "bg-muted")}>
                    {escalated[rf.id] ? "Escalated" : "Escalate"}
                  </button>
                </div>
              </div>
            ))}
            {(!patient.redFlags || patient.redFlags.length === 0) && (
              <div className="flex items-center gap-2 rounded-xl border border-border bg-card p-4 text-sm text-muted-foreground">
                <BadgeCheck className="size-5 text-emerald-500" /> No red flags detected for this patient.
              </div>
            )}
          </div>
        </div>
      )}

      {/* Bottom summary actions when relevant */}
      <div className="mt-6 rounded-2xl border border-border bg-card p-3.5 card-soft">
        <div className="flex items-center justify-between">
          <p className="text-xs font-semibold">Patient: {patient.name}</p>
          <StatusBadge variant={statusVariant(patient.status)} dot>{patient.status.replace("_", " ")}</StatusBadge>
        </div>
        <div className="mt-2.5 grid grid-cols-2 gap-2">
          <Button variant="outline" className="flex items-center gap-1.5" onClick={regenerateAi} disabled={regenerating}>
            <RotateCcw className={cn("size-4", regenerating && "animate-spin")} /> {regenerating ? "Regenerating…" : "Regenerate AI"}
          </Button>
          <Button className="flex items-center gap-1.5" onClick={() => {
            applyVerdict("accepted");
            updateCaseRecord(patient.id, { status: "IN_CONSULTATION" });
            addAudit(patient, "CONSULTATION_STARTED");
            setView("DOCTOR_CONSULTATION");
          }}><Check className="size-4" /> Start Consultation</Button>
        </div>
      </div>

      <div className="mt-4">
        <p className="mb-2 text-xs font-semibold text-muted-foreground">Other patients</p>
        <div className="flex flex-wrap gap-1.5">
          {caseQueue.filter((p) => p.id !== patient.id).slice(0, 4).map((p) => (
            <button key={p.id} onClick={() => summon(p.id)}
              className="flex items-center gap-1.5 rounded-full border border-border bg-card px-2.5 py-1 text-xs font-medium">
              <User className="size-3 text-muted-foreground" /> {p.name.split(" ")[0]}
            </button>
          ))}
          {caseQueue.filter((p) => p.id !== patient.id).length === 0 && (
            <p className="text-xs text-muted-foreground">No other patients in the queue.</p>
          )}
        </div>
      </div>
    </DoctorPageShell>
  );
}

function VerdictBtn({ icon: Icon, label, active, tone, onClick }: { icon: React.ComponentType<{ className?: string }>; label: string; active: boolean; tone: string; onClick: () => void }) {
  return (
    <button onClick={onClick}
      className={cn("flex flex-col items-center gap-1 rounded-xl border py-3 text-xs font-semibold transition-colors",
        active
          ? tone === "emerald" ? "border-emerald-500 bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10" : tone === "sky" ? "border-sky-500 bg-sky-50 text-sky-700 dark:bg-sky-500/10" : "border-red-500 bg-red-50 text-red-700 dark:bg-red-500/10"
          : "border-border bg-card text-muted-foreground")}>
      <Icon className="size-5" />
      {label}
    </button>
  );
}

function VerifiedBanner({ text }: { text: string }) {
  return (
    <div className="mt-3 flex items-center gap-2 rounded-xl border border-emerald-300/50 bg-emerald-50 p-3 text-xs text-emerald-800 dark:bg-emerald-500/10 dark:text-emerald-300">
      <BadgeCheck className="size-4" /> {text}
    </div>
  );
}

function NoteList({ title, items }: { title: string; items: ClinicalNote[] }) {
  return (
    <div className="mt-4">
      <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{title}</p>
      <div className="space-y-2">
        {items.map((n) => (
          <div key={n.id} className="rounded-xl border border-border bg-card p-3">
            <p className="text-sm">{n.content}</p>
            <p className="mt-1 text-[10px] text-muted-foreground">{new Date(n.timestamp).toLocaleString()}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
